export const experiences = [
    {
        id: 1,
        title: "Eco-Friendly Tours",
        category: "Sustainability",
        province: "Western Cape",
        location: "Cape Town – Table Mountain",
        date: "2025-06-01",
        time: "09:00 AM",
        description: "A guided eco-tour exploring sustainable practices in the Cape region.",
        theme: "Nature & Sustainability",
        price: 250,
        durationHours: 3,
        provider: "Green Cape Tours",
        image: "/images/exp/Eco-Friendly Tours in Western Cape.jpeg"
    },
    {
        id: 2,
        title: "Green Accommodations",
        category: "Sustainability",
        province: "Eastern Cape",
        location: "Addo National Park",
        date: "2025-07-15",
        time: "02:00 PM",
        description: "Stay at eco-lodges in the Eastern Cape with solar power and water-saving systems.",
        theme: "Eco-Living",
        price: 300,
        durationHours: 24,
        provider: "Eastern Eco Stays",
        image: "/images/exp/green accomodations at eastern cape.jpeg"
    },
    {
        id: 3,
        title: "Community Projects",
        category: "Sustainability",
        province: "Limpopo",
        location: "Polokwane Rural Villages",
        date: "2025-08-01",
        time: "10:00 AM",
        description: "Participate in local community farming and cultural exchange projects.",
        theme: "Community & Rural Life",
        price: 200,
        durationHours: 5,
        provider: "Limpopo Community Trust",
        image: "/images/exp/limpopo_community.jpg"
    },
    {
        id: 4,
        title: "Langa Cultural Festival",
        category: "Food & Drinks",
        province: "Western Cape",
        location: "Langa Township, Cape Town",
        date: "2025-06-15",
        time: "12:00 PM",
        description: "Experience traditional food, music, and local performances at Langa's biggest cultural event.",
        theme: "Food & Culture",
        price: 150,
        durationHours: 6,
        provider: "Langa Arts Council",
        image: "/images/exp/langa.jpeg"
    },
    {
        id: 5,
        title: "Khayelitsha Dance Show",
        category: "Food & Drinks",
        province: "Western Cape",
        location: "Khayelitsha, Cape Town",
        date: "2025-07-01",
        time: "07:00 PM",
        description: "A vibrant evening of township dance, live music, and local cuisine.",
        theme: "Township Nightlife",
        price: 200,
        durationHours: 3,
        provider: "Khayelitsha Dance Collective",
        image: "/images/exp/Khayelitsha Dance Show in Western Cape.jpeg"
    },
    {
        id: 6,
        title: "Gauteng Art Market",
        category: "Food & Drinks",
        province: "Gauteng",
        location: "Johannesburg CBD",
        date: "2025-07-15",
        time: "11:00 AM",
        description: "A bustling art and food market showcasing Gauteng's emerging creatives.",
        theme: "Art & Cuisine",
        price: 250,
        durationHours: 4,
        provider: "Jozi Creatives",
        image: "/images/exp/Gauteng Art Market.jpeg"
    },
    {
        id: 7,
        title: "Langa Cultural Festival",
        category: "History & Culture",
        province: "Western Cape",
        location: "Langa Township, Cape Town",
        date: "2025-08-01",
        time: "01:00 PM",
        description: "Celebrate Langa's deep cultural roots with heritage tours and live shows.",
        theme: "Heritage & Tradition",
        price: 550,
        durationHours: 7,
        provider: "Langa Heritage Association",
        image: "/images/exp/2.jpg"
    },
    {
        id: 8,
        title: "Khayelitsha Dance Show",
        category: "History & Culture",
        province: "Western Cape",
        location: "Khayelitsha, Cape Town",
        date: "2025-08-15",
        time: "06:00 PM",
        description: "Traditional and contemporary dance fused to tell Khayelitsha's cultural story.",
        theme: "Dance & Heritage",
        price: 800,
        durationHours: 3,
        provider: "Khayelitsha Cultural Collective",
        image: "/images/exp/Khayelitsha Dance Show in Western Cape.jpeg"
    },
    {
        id: 9,
        title: "Gauteng Art Market",
        category: "History & Culture",
        province: "Gauteng",
        location: "Johannesburg CBD",
        date: "2025-09-01",
        time: "10:00 AM",
        description: "Explore Johannesburg's art history through a vibrant market with live workshops.",
        theme: "Art & History",
        price: 2500,
        durationHours: 5,
        provider: "Jozi History Makers",
        image: "/images/exp/Gauteng Art Market.jpeg"
    },
    {
        id: 10,
        title: "Soweto Bicycle Tour",
        category: "Adventure",
        province: "Gauteng",
        location: "Soweto, Johannesburg",
        date: "2025-06-10",
        time: "08:30 AM",
        description: "Explore the vibrant streets of Soweto on a guided bicycle tour, visiting historical sites and local communities.",
        theme: "Urban Adventure",
        price: 350,
        durationHours: 4,
        provider: "Soweto Adventures",
        image: "/images/exp/Soweto Bicycle Tour.jpeg"
    },
    {
        id: 11,
        title: "Drakensberg Hiking Expedition",
        category: "Adventure",
        province: "KwaZulu-Natal",
        location: "Drakensberg Mountains",
        date: "2025-07-05",
        time: "07:00 AM",
        description: "Challenging hiking trails through the majestic Drakensberg mountains with breathtaking views.",
        theme: "Mountain Adventure",
        price: 600,
        durationHours: 8,
        provider: "Mountain Quest Tours",
        image: "/images/exp/Drakensberg Hiking Expedition.jpeg"
    },
    {
        id: 12,
        title: "Cango Caves Exploration",
        category: "Adventure",
        province: "Western Cape",
        location: "Oudtshoorn",
        date: "2025-08-20",
        time: "10:00 AM",
        description: "Explore the magnificent limestone formations in one of South Africa's most famous cave systems.",
        theme: "Underground Adventure",
        price: 280,
        durationHours: 3,
        provider: "Cango Adventures",
        image: "/images/exp/Cango Caves Exploration.jpeg"
    },
    {
        id: 13,
        title: "Wild Coast Horse Riding",
        category: "Adventure",
        province: "Eastern Cape",
        location: "Wild Coast",
        date: "2025-09-12",
        time: "09:30 AM",
        description: "Horseback riding along the pristine beaches and cliffs of the spectacular Wild Coast.",
        theme: "Coastal Adventure",
        price: 450,
        durationHours: 5,
        provider: "Wild Coast Trails",
        image: "/images/exp/Wild Coast Horse Riding.jpeg"
    },
    {
        id: 14,
        title: "Kruger National Park Safari",
        category: "Wildlife",
        province: "Mpumalanga",
        location: "Kruger National Park",
        date: "2025-06-22",
        time: "05:30 AM",
        description: "Early morning game drive to spot the Big Five in one of Africa's largest game reserves.",
        theme: "Wildlife Safari",
        price: 750,
        durationHours: 6,
        provider: "Kruger Safaris",
        image: "/images/exp/Kruger National Park Safari.jpeg"
    },
    {
        id: 15,
        title: "Penguin Colony Tour",
        category: "Wildlife",
        province: "Western Cape",
        location: "Boulders Beach",
        date: "2025-07-18",
        time: "02:00 PM",
        description: "Get up close with African penguins in their natural habitat at Boulders Beach.",
        theme: "Marine Wildlife",
        price: 120,
        durationHours: 2,
        provider: "Coastal Wildlife Tours",
        image: "/images/exp/Penguin Colony Tour.jpeg"
    },
    {
        id: 16,
        title: "Addo Elephant Experience",
        category: "Wildlife",
        province: "Eastern Cape",
        location: "Addo Elephant National Park",
        date: "2025-08-08",
        time: "08:00 AM",
        description: "Specialized tour focusing on elephant behavior and conservation efforts in Addo.",
        theme: "Elephant Conservation",
        price: 420,
        durationHours: 5,
        provider: "Addo Elephant Tours",
        image: "/images/exp/Addo Elephant Experience.jpeg"
    },
    {
        id: 18,
        title: "Traditional Xhosa Cooking",
        category: "Food & Drinks",
        province: "Eastern Cape",
        location: "Port Elizabeth Townships",
        date: "2025-06-05",
        time: "11:00 AM",
        description: "Learn to cook traditional Xhosa dishes with local chefs in an authentic setting.",
        theme: "Cultural Cuisine",
        price: 300,
        durationHours: 3,
        provider: "Taste of Xhosa",
        image: "/images/exp/Traditional Xhosa Cooking in Eastern Cape.jpeg"
    },
    {
        id: 19,
        title: "Wine Tasting in Stellenbosch",
        category: "Food & Drinks",
        province: "Western Cape",
        location: "Stellenbosch Winelands",
        date: "2025-07-22",
        time: "01:00 PM",
        description: "Guided tour of premium wine estates in Stellenbosch with tastings and food pairings.",
        theme: "Wine Culture",
        price: 480,
        durationHours: 4,
        provider: "Stellenbosch Wine Tours",
        image: "/images/exp/Wine Tasting in Stellenbosch.jpeg"
    },
    {
        id: 20,
        title: "Cape Malay Cooking Experience",
        category: "Food & Drinks",
        province: "Western Cape",
        location: "Bo-Kaap, Cape Town",
        date: "2025-08-14",
        time: "10:30 AM",
        description: "Hands-on cooking class learning traditional Cape Malay recipes in the colorful Bo-Kaap district.",
        theme: "Cultural Cooking",
        price: 350,
        durationHours: 3,
        provider: "Bo-Kaap Kitchen",
        image: "/images/exp/Cape Malay Cooking Experience in Western Cape.jpeg"
    },
    {
        id: 21,
        title: "Zulu Cultural Village",
        category: "History & Culture",
        province: "KwaZulu-Natal",
        location: "Durban Surrounds",
        date: "2025-06-18",
        time: "09:00 AM",
        description: "Immerse yourself in Zulu traditions, dance, and storytelling at an authentic cultural village.",
        theme: "Zulu Heritage",
        price: 320,
        durationHours: 6,
        provider: "Zulu Experience",
        image: "/images/exp/Zulu Cultural Village in KwaZulu-Natal.jpeg"
    },
    {
        id: 22,
        title: "Robben Island Tour",
        category: "History & Culture",
        province: "Western Cape",
        location: "Robben Island",
        date: "2025-07-07",
        time: "11:00 AM",
        description: "Visit the former prison where Nelson Mandela was held, with ex-political prisoner guides.",
        theme: "Historical Journey",
        price: 400,
        durationHours: 5,
        provider: "Robben Island Museum",
        image: "/images/exp/Robben Island Tour in Western Cape.jpeg"
    },
    {
        id: 23,
        title: "Apartheid Museum",
        category: "History & Culture",
        province: "Gauteng",
        location: "Johannesburg",
        date: "2025-08-25",
        time: "10:00 AM",
        description: "Guided tour through the comprehensive exhibits on South Africa's apartheid history.",
        theme: "Historical Education",
        price: 120,
        durationHours: 3,
        provider: "Apartheid Museum Guides",
        image: "/images/exp/Apartheid Museum in Gauteng.jpeg"
    },
    {
        id: 24,
        title: "San Rock Art Tour",
        category: "History & Culture",
        province: "Western Cape",
        location: "Cederberg Mountains",
        date: "2025-09-15",
        time: "09:30 AM",
        description: "Explore ancient San rock art sites with knowledgeable guides explaining the symbolism.",
        theme: "Ancient History",
        price: 280,
        durationHours: 4,
        provider: "Cederberg Heritage Tours",
        image: "/images/exp/San Rock Art Tour in Western Cape.jpeg"
    },
    {
        id: 25,
        title: "Sustainable Farming Experience",
        category: "Sustainability",
        province: "Western Cape",
        location: "Franschhoek Valley",
        date: "2025-06-28",
        time: "08:00 AM",
        description: "Hands-on experience at an organic farm practicing sustainable agriculture methods.",
        theme: "Eco-Farming",
        price: 220,
        durationHours: 5,
        provider: "Green Valley Farm",
        image: "/images/exp/farming.jpg"
    },
    {
        id: 26,
        title: "Ocean Cleanup Initiative",
        category: "Sustainability",
        province: "KwaZulu-Natal",
        location: "Durban Beachfront",
        date: "2025-07-14",
        time: "08:30 AM",
        description: "Participate in a beach cleanup and learn about marine conservation efforts.",
        theme: "Marine Conservation",
        price: 100,
        durationHours: 3,
        provider: "Ocean Guardians",
        image: "/images/exp/ocean.jpg"
    },
    {
        id: 27,
        title: "Solar Energy Workshop",
        category: "Sustainability",
        province: "Gauteng",
        location: "Pretoria",
        date: "2025-08-09",
        time: "10:00 AM",
        description: "Interactive workshop on solar energy implementation for homes and businesses.",
        theme: "Renewable Energy",
        price: 180,
        durationHours: 4,
        provider: "Solar Solutions SA",
        image: "/images/exp/solar.jpg"
    },
    {
        id: 28,
        title: "Indigenous Plant Walk",
        category: "Sustainability",
        province: "Western Cape",
        location: "Kirstenbosch Gardens",
        date: "2025-09-05",
        time: "09:00 AM",
        description: "Guided walk through Kirstenbosch focusing on indigenous plants and their traditional uses.",
        theme: "Botanical Education",
        price: 150,
        durationHours: 2,
        provider: "Kirstenbosch Guides",
        image: "/images/exp/flower.jpeg"
    },
    {
        id: 29,
        title: "Township Art Tour",
        category: "Arts & Culture",
        province: "Western Cape",
        location: "Gugulethu Township",
        date: "2025-06-12",
        time: "11:00 AM",
        description: "Explore vibrant street art and visit local artists' studios in Gugulethu township.",
        theme: "Urban Art",
        price: 200,
        durationHours: 3,
        provider: "Gugulethu Art Collective",
        image: "/images/exp/Township Art Tour.jpeg"
    },
    {
        id: 30,
        title: "Drumming Workshop",
        category: "Arts & Culture",
        province: "Gauteng",
        location: "Alexandra Township",
        date: "2025-07-28",
        time: "02:00 PM",
        description: "Learn traditional African drumming techniques from local musicians.",
        theme: "Musical Heritage",
        price: 180,
        durationHours: 2,
        provider: "Alexandra Drum Circle",
        image: "/images/exp/Drumming Workshop.jpeg"
    },
    {
        id: 31,
        title: "Beadwork Craft Class",
        category: "Arts & Culture",
        province: "KwaZulu-Natal",
        location: "Pietermaritzburg",
        date: "2025-08-17",
        time: "10:30 AM",
        description: "Create traditional Zulu beadwork with skilled local artisans.",
        theme: "Traditional Crafts",
        price: 220,
        durationHours: 3,
        provider: "Zulu Beadwork Co-op",
        image: "/images/exp/Beadwork Craft Class.jpeg"
    },
    {
        id: 32,
        title: "Jazz Night in Soweto",
        category: "Arts & Culture",
        province: "Gauteng",
        location: "Soweto",
        date: "2025-09-22",
        time: "07:00 PM",
        description: "Experience authentic South African jazz at a legendary Soweto venue.",
        theme: "Live Music",
        price: 250,
        durationHours: 4,
        provider: "Soweto Jazz Club",
        image: "/images/exp/Jazz Night in Soweto.jpeg"
    },
    {
        id: 35,
        title: "Zip-lining Tour",
        category: "Adventure",
        province: "Mpumalanga",
        location: "Sabie Valley",
        date: "2025-08-28",
        time: "09:00 AM",
        description: "Thrilling zip-lining experience through the lush Sabie Valley forest canopy.",
        theme: "Forest Adventure",
        price: 380,
        durationHours: 3,
        provider: "Valley Zip Adventures",
        image: "/images/exp/Zip-lining Tour.jpeg"
    }
];